export const ADD_TASK = 'ADD_TASK'
export const CHECK_TASK = 'CHECK_TASK'
export const UNCHECK_TASK = 'UNCHECK_TASK'
export const DELETE_TASK = 'DELETE_TASK'
export const FILTER_TASKS = 'FILTER_TASKS'
export const UNFILTER_TASKS = 'UNFILTER_TASKS'